# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96be2fac7c7f120dafa034d1a2529d6aace86de35b4438983e239e9329223dc185c366c88c7ca9a9cf2840c171122aceec2229addb70370fd2f2d5a0ceed29ca

test:
  secret_key_base: 695bb8a4d76170fa14609f7aea742b56230010f31b4e7b0528213aa4cee779894913bb34d757f0281ab541517277c2510f6d4c7d06b0837654103c5728320ffb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
